### ISSUE TITLE
V 1.5 live patch broked it xD

### ISSUE THREAD

**Issue by coolmoo** [encode32/WurmEsp#3]
Basically the clickable menu no longer works and the esp highlights no longer works.
Any work arounds?

**Comment by encode32** [comment]
Need to look at it.

**Comment by encode32** [comment]
Working again, will commit once resolve something.

**Comment by coolmoo** [comment]
wow love how fast you managed to do that any link I can send you some money to?

**Comment by encode32** [comment]
HotFix is ready.

I have a public link for paypal donations, thanks for your support. https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3SPZLLZ3JNC3N
