### ISSUE TITLE
Exeption in WurmEspMod.init()

### ISSUE THREAD

**Issue by LegionUA** [encode32/WurmEsp#4]
Update 1.5 breaks my precious...

![default](https://user-images.githubusercontent.com/9502129/31431245-c5cfefbc-ae7b-11e7-9df2-1c3d1b011a07.png)

**Comment by encode32** [comment]
Need to look at it.

**Comment by encode32** [comment]
Working again, will commit once resolve something.

**Comment by LegionUA** [comment]
I tried to write some kostyli, but it still not working. I think i not fully understand, how HookManager works now.

**Comment by encode32** [comment]
HotFix ready.
