### ISSUE TITLE
names of creatures, and treasure chests get errors

### ISSUE THREAD

**Issue by JDBooker** [encode32/WurmEsp#5]
The names also seem to change each time the animal is taking damage from attacks, and passing the LOD distance points toward or away from them.
The animals graphic in the target window goes "missing Image" after it takes damage.
Tested attacking; 3 wildcats, 2 Pigs, 1 Hen.
LOD tested: 1 supreme treasure chest (cos i happened to see it highlight and rushed toward it)

Example image; https://i.imgur.com/Cijwi7z.jpg

Current mods loaded;
Compass
Disabled Tree Collisions
Fixed Connecting to Sklotopolis
Livemap
Nowinter
Timelock
Toolbelt
Tooltips

Everything was fine before the Wurm update.
Everything was fine after the update, without WurmESP.
I am currently pulling all the mods and leaving just WurmESP, then putting them on 1 at a time to see when it happens... will report back in a bit.

**Comment by JDBooker** [comment]
Update...
https://i.imgur.com/2z5uDvG.jpg
With no mods apart from WurmESP

Video showing the hell horses and a cow names with errors (hell horses throughout, cow changes at ~1m24s)
https://1drv.ms/v/s!AgBX8nv0qvwuhWpK8raPffexStdz

**Comment by JDBooker** [comment]
Video showing the hell horses and a cow names with errors (hell horses throughout, cow changes at ~1m24s)
URL coming (slow internet upload)

**Comment by encode32** [comment]
Are you on your own server?

**Comment by JDBooker** [comment]
on sklotopolis
I was on my machine at my second house. i am home now and the same thing is happening.
I will load up a test server and see what happens there

**Comment by encode32** [comment]
Ill check on sklo.

**Comment by JDBooker** [comment]
Yup still happening on a brand new unmodded test server.
https://i.imgur.com/obuGipf.jpg
even the admin gets it
https://i.imgur.com/vnMczQo.jpg

**Comment by encode32** [comment]
Still can't replicate this error on my side, this mod don't edit in any way the mob names.

Anyway if i can help you, fell free to ask.

**Comment by JDBooker** [comment]
strange, i've run it on 3 different PCs and get the error, whether it's a public server or a clean new one of my own.
i've redownloaded mod loader and esp incase of a corruption.
still does it. lol
remove esp and it's fine. remove all mods and have just esp and it does it again.

update: i just tried on an old laptop .. same there too! lol
trouble is it's intermittent, but eventually it'll happen if you keep hovering.
maybe it's some regional differences in the UK (?)

**Comment by JDBooker** [comment]
Most likely it's a memory address that being overwritten somehow,

**Comment by encode32** [comment]
Did you tried with a vanilla game? not even modlauncher?

**Comment by JDBooker** [comment]
any server with mod launcher and all the mods except esp, is fine.
i haven't tried running esp without the mod launcher as i don't know how to install mods directly.

**Comment by encode32** [comment]
I mean, game w/o any mods, and see if it happends.

**Comment by JDBooker** [comment]
no it doesn't happen

**Comment by JDBooker** [comment]
Vanilla game no mods = fine.
Modloader + no mods = fine.
Modloader + esp = intermittent name corruption.
Modloader + livemap + toolbelt + timelock + compass + disabled collision = fine.
Modloader + all the other mods + esp = intermittent name corruption.

Tried on 4 separate machines with 4 separate steam accounts.
3 AMD PCs, 1 intel laptop. all the same results.
:)

**Comment by encode32** [comment]
You are not alone, i'm collecting all the info from 2 more people to fix this issue.

**Comment by encode32** [comment]
Can you try this pre-release test build? https://github.com/encode32/WurmEsp/releases/tag/0.0.7d-test

**Comment by encode32** [comment]
Lets transport this issue to https://github.com/encode32/WurmEsp/issues/7
