### ISSUE TITLE
Xray PLS

### ISSUE THREAD

**Issue by Pamucuk** [encode32/WurmEsp#6]
İ want to back xray 
İ cant play without xray

**Comment by encode32** [comment]
I'm working on this, will have a new version with xray again.

**Comment by Pamucuk** [comment]
İm still wating for xyray 
Ty very much

**Comment by encode32** [comment]
You are still waiting? i'm doing this for free, feel a bit rude.

**Comment by LegionUA** [comment]
If you so need xray, you can try turn up showHiddenOre option in livemap mod.
![default](https://user-images.githubusercontent.com/9502129/31572975-bb299838-b0ba-11e7-9c4a-c217f83e6668.png)

**Comment by Pamucuk** [comment]
Legion eu = thank you very much you are life saver
